name: .NET Desktop CI/CD for Data Logger

on:
  push:
    branches: [ "main", "develop" ] 
  pull_request:
    branches: [ "main" ] 

jobs:
  build-and-test:
    runs-on: windows-latest

    services:
      opcua-server: # Dit is de naam die je kunt gebruiken om de service te adresseren (kan ook localhost zijn)
        image: ghcr.io/opcfoundation/uanetstandard/refserver:latest
        ports:
          - 62541:62541

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2
      with:
        nuget-version: 'latest' 

    - name: Restore NuGet packages
      run: nuget restore "Data Logger/Data Logger.sln"

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x86 

    - name: Build solution
      run: msbuild "Data Logger/Data Logger.sln" /p:Configuration=Release /p:Platform="Any CPU"
      
    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1.2 

    - name: Run Unit Tests
      run: vstest.console.exe "DataLogger.Tests/bin/Release/DataLogger.Tests.dll" /TestCaseFilter:"Category!=IntegrationTest" /Logger:trx /ResultsDirectory:"UnitTestResults"

    - name: Upload Unit Test Results
      if: always() 
      uses: actions/upload-artifact@v4
      with:
        name: unit-test-results
        path: TestResults/**/*.trx

    - name: Run Integration Tests
      # Deze tests zullen nu proberen te verbinden met de OPC UA server die als service draait.
      # De service is typisch bereikbaar op 'localhost:<host_port>' binnen de job.
      run: vstest.console.exe "DataLogger.Tests/bin/Release/DataLogger.Tests.dll" /TestCaseFilter:"Category=IntegrationTest" /Logger:trx /ResultsDirectory:"IntegrationTestResults"
      env:
        # Stel een omgevingsvariabele in die je tests kunnen gebruiken om het endpoint te bepalen.
        OPCUA_TEST_SERVER_ENDPOINT: "opc.tcp://localhost:62541/Quickstarts/ReferenceServer"
        # Voeg een variabele toe om aan je testcode (DockerTestHelper) te laten weten dat het in CI draait
        # en de Docker container NIET zelf moet beheren.
        CI_ENVIRONMENT: "true"

    - name: Upload Integration Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: integration-test-results
        path: IntegrationTestResults/**/*.trx

    - name: Upload Build Artifact (Data Logger Application)
      uses: actions/upload-artifact@v4
      with:
        name: data-logger-application
        path: | 
          Data Logger/bin/Release/**/*.exe
          Data Logger/bin/Release/**/*.dll
          Data Logger/bin/Release/**/*.config
          Data Logger/bin/Release/Logs 
          Data Logger/bin/Release/LoggedData 
          Data Logger/bin/Release/CertificateStores 
        
        
        
        
        
