name: .NET Desktop CI - Build, Unit Test, and Package

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-package:
    runs-on: windows-latest 
    
    env: # Omgevingsvariabelen indien nog nodig voor andere stappen, OPC UA specifieke zijn nu minder relevant
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true" # Versnelt dotnet tool commando's een beetje
      DOTNET_NOLOGO: "true"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2
      with:
        nuget-version: 'latest'

    - name: Restore NuGet packages
      run: nuget restore "Data Logger/Data Logger.sln"

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x86 

    - name: Build solution
      run: msbuild "Data Logger/Data Logger.sln" /p:Configuration=Release /p:Platform="Any CPU"

    - name: List Build Output Structure
      shell: pwsh
      run: |
        Get-ChildItem -Recurse -Path "./" | Select-Object FullName
        Write-Host "--- Verwachte Release Directory Inhoud ---"
        Get-ChildItem -Path "Data Logger/Data Logger/bin/Release" -ErrorAction SilentlyContinue

    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1.2 

    - name: Run Unit Tests (excluding IntegrationTests)
      run: vstest.console.exe "DataLogger.Tests/bin/Release/DataLogger.Tests.dll" /TestCaseFilter:"Category!=IntegrationTest" /Logger:trx /ResultsDirectory:"TestResults/UnitTests"

    - name: Upload Unit Test Results
      if: always() 
      uses: actions/upload-artifact@v4
      with:
        name: unit-test-results
        path: TestResults/UnitTests/**/*.trx
        
    - name: Create Portable Package Directory
      run: mkdir ./portable-package

    - name: Copy Build Artifacts to Portable Package Directory
      shell: pwsh
      run: |
        $releaseDir = "Data Logger/bin/Release"
        if (-not (Test-Path $releaseDir)) {
          Write-Error "Fout: Release directory '$releaseDir' niet gevonden. De build is mogelijk mislukt of het output pad is incorrect."
          exit 1
        }
        Write-Host "Kopiëren van bestanden uit '$releaseDir' naar './portable-package'"
        Get-ChildItem -Path "$releaseDir" -Filter "*.exe" | Copy-Item -Destination "./portable-package" -ErrorAction Stop
        Get-ChildItem -Path "$releaseDir" -Filter "*.dll" | Copy-Item -Destination "./portable-package" -ErrorAction Stop
        Get-ChildItem -Path "$releaseDir" -Filter "*.config" | Copy-Item -Destination "./portable-package" -ErrorAction Stop
        if (Test-Path "$releaseDir/Logs") {
          Write-Host "Kopiëren van Logs map..."
          Copy-Item -Path "$releaseDir/Logs" -Destination "./portable-package" -Recurse -Force -ErrorAction SilentlyContinue
        }
        if (Test-Path "$releaseDir/LoggedData") {
          Write-Host "Kopiëren van LoggedData map..."
          Copy-Item -Path "$releaseDir/LoggedData" -Destination "./portable-package" -Recurse -Force -ErrorAction SilentlyContinue
        }
        if (Test-Path "$releaseDir/CertificateStores") {
          Write-Host "Kopiëren van CertificateStores map..."
          Copy-Item -Path "$releaseDir/CertificateStores" -Destination "./portable-package" -Recurse -Force -ErrorAction SilentlyContinue
        }
        Write-Host "Bestanden succesvol gekopieerd naar ./portable-package"

    - name: Zip Portable Package
      shell: pwsh
      run: Compress-Archive -Path ./portable-package/* -DestinationPath ./data-logger-portable.zip -Force -ErrorAction Stop

    - name: Upload Portable Package Artifact
      uses: actions/upload-artifact@v4
      with:
        name: data-logger-portable-zip
        path: ./data-logger-portable.zip
