name: .NET Desktop CI/CD for Data Logger

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2
      with:
        nuget-version: 'latest'

    - name: Restore NuGet packages
      run: nuget restore "Data Logger/Data Logger.sln"

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x86 # Of x64, afhankelijk van je project

    - name: Build solution
      run: msbuild "Data Logger/Data Logger.sln" /p:Configuration=Release /p:Platform="Any CPU"

    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1.2

    - name: Run Unit Tests (excluding IntegrationTests)
      run: vstest.console.exe "DataLogger.Tests/bin/Release/DataLogger.Tests.dll" /TestCaseFilter:"Category!=IntegrationTest" /Logger:trx /ResultsDirectory:"UnitTestResults"
      # Deze stap faalt de workflow als unit tests falen.
      # Zorg ervoor dat je unit tests de categorie "IntegrationTest" NIET hebben,
      # of een andere categorie hebben zoals "Unit" en je filtert daarop.

    - name: Upload Unit Test Results
      if: always() # Upload altijd, ook als tests falen, voor analyse
      uses: actions/upload-artifact@v4
      with:
        name: unit-test-results
        path: UnitTestResults/**/*.trx

    # --- Integratietest stappen zijn hier verwijderd ---
    # - name: Run Integration Tests ...
    # - name: Upload Integration Test Results ...
    # - name: Check Integration Test Outcome ...

    - name: Upload Build Artifact (Data Logger Application)
      uses: actions/upload-artifact@v4
      with:
        name: data-logger-application
        path: |
          Data Logger/Data Logger/bin/Release/**/*.exe
          Data Logger/Data Logger/bin/Release/**/*.dll
          Data Logger/Data Logger/bin/Release/**/*.config
          # Voeg hier andere bestanden toe die je nodig hebt voor je artefact
          # Data Logger/Data Logger/bin/Release/Logs
          # Data Logger/Data Logger/bin/Release/LoggedData
          # Data Logger/Data Logger/bin/Release/CertificateStores
