name: .NET CI/CD for Data Logger

on:
  push: 
    branches: [ main, develop ]
  pull_request: 
    branches: [ main, develop ]
  workflow_dispatch: 

jobs:
  build-and-unit-test:
    name: Build & Unit Test
    runs-on: windows-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
      with:
        nuget-version: 'latest'

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore NuGet packages for Solution
      run: nuget restore "Data Logger/Data Logger.sln"

    - name: Build Solution with MSBuild
      run: msbuild "Data Logger/Data Logger.sln" /p:Configuration=Release /p:Platform="Any CPU"

    - name: Run Unit Tests with VSTest.Console
      run: |
        $vstestPath = Get-Command vstest.console.exe -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Source
        if (-not $vstestPath) {
            $vsInstallPaths = @(
                "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\TestPlatform",
                "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2022\Professional\Common7\IDE\Extensions\TestPlatform",
                "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2022\Community\Common7\IDE\Extensions\TestPlatform",
                "${env:ProgramFiles}\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\TestPlatform",
                "${env:ProgramFiles}\Microsoft Visual Studio\2022\Professional\Common7\IDE\Extensions\TestPlatform",
                "${env:ProgramFiles}\Microsoft Visual Studio\2022\Community\Common7\IDE\Extensions\TestPlatform",

                "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow",
                "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\TestWindow",
                "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow"
            )
            foreach ($path in $vsInstallPaths) {
                $testExe = Join-Path $path "vstest.console.exe"
                if (Test-Path $testExe) {
                    $vstestPath = $testExe
                    break
                }
            }
        }
        
        if (-not $vstestPath) {
            Write-Error "VSTest.Console.exe niet gevonden. Controleer de paden of installeer 'Microsoft.TestPlatform' NuGet-pakket in testproject en probeer 'dotnet test'."
            exit 1
        }

        Write-Host "VSTest.Console.exe gevonden op: $vstestPath"
        
        $testDllPath = "DataLogger.Tests/bin/Release/DataLogger.Tests.dll" # Pas dit pad aan!

        $testFilter = '/TestCaseFilter:"FullyQualifiedName~DataLogger.IntegrationTest"'

        $resultFile = "unit_test_results.trx"

        Write-Host "Test DLL Pad: $testDllPath"
        Write-Host "Filter: $testFilter"
        Write-Host "Resultaat Bestand: $resultFile"
        
        & $vstestPath $testDllPath /Logger:"trx;LogFileName=$resultFile" $testFilter /EnableCodeCoverage /InIsolation
      shell: pwsh

    - name: Upload Unit Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: unit-test-results
        path: DataLogger.Tests/TestResults/unit_test_results.trx

  integration-test:
    name: Integration Test with Docker OPC UA Server
    runs-on: ubuntu-latest 
    needs: build-and-unit-test 

    services: 
      docker:
        image: docker:dind 
        options: --privileged 

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '4.8.1' 

    - name: Restore dependencies for Test Project
      run: dotnet restore ./DataLogger.Tests 

    - name: Build Test Project (nodig als niet alles gebuild is in vorige job)
      run: dotnet build ./DataLogger.Tests --configuration Release --no-restore

    - name: Check Docker Version
      run: docker --version

    - name: Pull OPC UA Reference Server Image
      run: docker pull ghcr.io/opcfoundation/uanetstandard/refserver:latest
      
    - name: Run Integration Tests
      run: |
        echo "Starting Integration Tests..."
        dotnet test ./DataLogger.Tests --configuration Release --no-build --verbosity normal --filter "FullyQualifiedName~IntegrationTests"
        
      timeout-minutes: 15
